### ISSUE TITLE
Add support for `Ninja Multi-Config` generator

### ISSUE THREAD

**Issue by ktetzlaff** [darcamo/cmake-integration#3]
CMake version 3.17 added the `Ninja Multi-Config` generator (https://cmake.org/cmake/help/latest/generator/Ninja%20Multi-Config.html?highlight=ninja%20multi#generator:Ninja%20Multi-Config) which supports multiple build types in a single binary (build) directory (currently: `Debug`, `Release`, `ReleaseWithDebInfo`).

When using cmake-integration with a `Ninja Multi-Config` build directory, it should offer targets for all  combinations of _target name_ and _build type/config_.

**Comment by darcamo** [comment]
When reading the configurations for a given configure preset we get a vector of configurations. I don't use Ninja Multi-Config myself and thus this vector of configurations always has only one element. Therefore, currently I just get the first element in the vector of configurations.

In the case of multi-config, this vector has three elements. The current implementation just gets the first one, which is likely the debug build.

I took a look at which changes would be required to support this. One limitation at the moment is that when configuring the user selects the desired preset from a list of **configure presets**. Then, when building, I just assume that there is a **build preset** with the same name of the configure preset and use that. 

One way to solve this issue is to have a build preset for each build type (Debug, Release, etc), all referencing the same configure preset using the Ninja Multi-Config generator. Then the code in cmake-integration would need to change to read build preset names, instead of configure preset names. With this, the usage would be similar to what we have currently. But I don't know how it would work when presets are not employed.

Could you elaborate how you usually configure and build with different configurations from the command line using the Ninja Multi-Config generator.

**Comment by ktetzlaff** [comment]
Using a build dir generated by the _Ninja Multi-Config_ generator is (by default) no different than using the normal Ninja generator. You can just say:
```
cmake --build build # with build dir: 'build'
```
or
```
cd build
ninja
```
This will, by default, build the `Debug` target (you can change this by adding e.g. `-DCMAKE_DEFAULT_BUILD_TYPE=Release` to the configure step).

To build the other configurations, cmake supports the `--config <buildtype>` option. E.g.:
```
cmake --build build --config Release # or: RelWithDebInfo
```
or:
```
cd build
ninja -f build-Release.ninja
```

JFYI: There are some additional variables to control the Multi Config build. The more interesting ones are:

- CMAKE_CONFIGURATION_TYPES :: Specifies the total set of configurations to
  build (default: `Debug;Release;RelWithDebInfo`).

- CMAKE_DEFAULT_CONFIGS :: Specifies a semicolon-separated list of
  configurations to build for a target in build.ninja if no :<Config> suffix is
  specified.

**Comment by ktetzlaff** [comment]
Looking at _<builddir>/.cmake/api/v1/reply/codemodel-v2-*.json_, the multi config variant just has muliple elements in the `configurations` list:

I.e. for a project with targets `foo` and `bar` the _normal_ Ninja generator has (json converted to yaml for better readability):
```
configurations:
- name: "Debug"
  directories: [...]
  projects: [...]
  targets:
  - name: "foo"
    ...:
  - name: "bar"
    ...:
```
whereas the _Multi Config_ case has:
```
configurations:
- name: "Debug"
  directories: [...]
  projects: [...]
  targets:
  - name: "foo"
    ...:
  - name: "bar"
    ...:
- name: "Release"
  directories: [...]
  projects: [...]
  targets:
  - name: "foo"
    ...:
  - name: "bar"
    ...:
- name: "RelWithDebInfo"
  directories: [...]
  projects: [...]
  targets:
  - name: "foo"
    ...:
  - name: "bar"
    ...:
```

So what would make sense is to construct a _Multi Config_ target list containing elements like:
* all/Debug
* all/Release
* all/RelWithDebInfo
* foo/Debug
* foo/Release
* foo/RelWithDebInfo
* bar/Debug
* bar/Release
* bar/RelWithDebInfo

(or put the config at the beginning - this is a personal preference).
